packaging_format = 2

id = "freedit"
name = "Freedit"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "0.4.5~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "MIT"
website = "https://freedit.eu/"
demo = "https://freedit.eu/"
code = "https://github.com/freedit-org/freedit"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/freedit"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/freedit-org/freedit/releases/download/v0.4.5/freedit-v0.4.5-x86_64-unknown-linux-gnu.zip"
        sha256 = "8d7d406638833ca7f62d41b1b15c7c3a259fc802a61c9b12de86d6fb4709d973"
        autoupdate.strategy = "latest_github_tag"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3001

    [resources.apt]
    packages = "libssl-dev libc6"
